import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

interface CueItem {
  type: string;
  title: string;
  author?: string;
  duration?: string;
  note?: string;
  hasPdf?: boolean;
  hasAudio?: boolean;
}

/**
 * 큐시트를 스타일이 있는 PDF로 생성합니다.
 */
export async function generateCueSheetPdf(
  title: string,
  items: CueItem[],
  totalDuration: string
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const pageWidth = 595.28; // A4
  const pageHeight = 841.89;
  const margin = 50;
  const colWidths = [35, 70, 180, 100, 50, 100]; // #, Type, Title, Artist, Time, Note

  const dark = rgb(0.176, 0.161, 0.149);   // #2D2926
  const gold = rgb(0.902, 0.78, 0.612);    // #E6C79C
  const gray = rgb(0.47, 0.44, 0.42);      // #78716A
  const lightBg = rgb(0.98, 0.976, 0.965); // #FAF9F6
  const white = rgb(1, 1, 1);

  let page = pdfDoc.addPage([pageWidth, pageHeight]);
  let y = pageHeight - margin;

  // === Header ===
  // Gold bar
  page.drawRectangle({ x: 0, y: pageHeight - 8, width: pageWidth, height: 8, color: gold });

  // Title
  page.drawText(title || 'Setlist', { x: margin, y: y - 20, font: fontBold, size: 22, color: dark });
  y -= 28;

  // Subtitle
  const subtitle = `${items.length} items · Total: ${totalDuration} · ibiGband Smart Cue`;
  page.drawText(subtitle, { x: margin, y: y - 12, font, size: 9, color: gray });
  y -= 30;

  // Divider
  page.drawRectangle({ x: margin, y, width: pageWidth - margin * 2, height: 1, color: gold });
  y -= 20;

  // === Table Header ===
  const headers = ['#', 'Type', 'Title', 'Artist', 'Time', 'Note'];
  const headerY = y;
  page.drawRectangle({ x: margin, y: headerY - 4, width: pageWidth - margin * 2, height: 22, color: dark });

  let xPos = margin + 8;
  headers.forEach((h, i) => {
    page.drawText(h, { x: xPos, y: headerY + 2, font: fontBold, size: 8, color: white });
    xPos += colWidths[i];
  });
  y -= 28;

  // === Table Rows ===
  const typeLabels: Record<string, string> = {
    sheet: 'Sheet', mr: 'MR/Track', bgm: 'BGM', transcript: 'Script', guide: 'Guide'
  };

  const truncate = (text: string, maxLen: number) => {
    if (!text) return '';
    // Approximate: each char ~5.5px at size 9
    const maxChars = Math.floor(maxLen / 5.5);
    return text.length > maxChars ? text.slice(0, maxChars - 2) + '..' : text;
  };

  for (let i = 0; i < items.length; i++) {
    if (y < margin + 40) {
      // New page
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      y = pageHeight - margin;
    }

    const item = items[i];
    const rowBg = i % 2 === 0 ? lightBg : white;
    page.drawRectangle({ x: margin, y: y - 4, width: pageWidth - margin * 2, height: 22, color: rowBg });

    xPos = margin + 8;
    const rowData = [
      String(i + 1),
      typeLabels[item.type] || item.type,
      truncate(item.title, colWidths[2] - 10),
      truncate(item.author || '', colWidths[3] - 10),
      item.duration || '-',
      truncate(item.note || '', colWidths[5] - 10),
    ];

    rowData.forEach((text, ci) => {
      const f = ci === 0 || ci === 2 ? fontBold : font;
      const c = ci === 2 ? dark : gray;
      page.drawText(text, { x: xPos, y: y + 2, font: f, size: ci === 0 ? 10 : 8, color: c });
      xPos += colWidths[ci];
    });

    y -= 24;
  }

  // === Footer ===
  y -= 20;
  if (y < margin + 30) {
    page = pdfDoc.addPage([pageWidth, pageHeight]);
    y = pageHeight - margin;
  }
  page.drawRectangle({ x: margin, y, width: pageWidth - margin * 2, height: 1, color: rgb(0.9, 0.9, 0.9) });
  y -= 16;
  page.drawText('Generated by ibiGband Smart Setlist · ibigband.com', { x: margin, y, font, size: 7, color: gray });

  return pdfDoc.save();
}
